### ISSUE TITLE
Unable to autocomplete when opening new java file

### ISSUE THREAD

**Issue by TV12mac** [neoclide/coc-java#130]
[coc.nvim]: Uncaught exception: ENOENT: no such file or directory, lstat '../libexec/openjdk.jdk/Contents/Home/bin/javac'
Im on MacOS big sur and when i create a new file for example nvim testclass.java. The error I showed above appears each time and the autocomplete does not work

**Comment by sakshampuri** [comment]
I've got the same issue on big sur

**Comment by sakshampuri** [comment]
For me, it was because brew set a symlink which you might have as well added as PATH to your zsh config. I don't know why the symlink is not working for it to find the executable but I have just added the absolute path to my path variable for now. 
You can find the absolute path by following the symlink. Following was my path which I put in my config and it's working after that
```
export PATH="/usr/local/opt/openjdk/libexec/openjdk.jdk/Contents/Home/bin:$PATH"
```

**Comment by TV12mac** [comment]
This worked for me. I don't have jdt.ls downloaded so its doing that now. Thanks for your help man appreciate it :-D
