### ISSUE TITLE
while loop auto complete

### ISSUE THREAD

**Issue by linhanwang** [neoclide/coc-java#218]
When I type whi and use enter to autocomplete, the result always be
wwhile (condition) {

}
I don't know whether it's a bug.

**Comment by Rider-kuuga** [comment]
I also met this problem (

**Comment by codebysandwich** [comment]
@linhanwang @Rider-kuuga me too, did you solved this question? 😭

**Comment by Rider-kuuga** [comment]
@codebysandwich basically, I try not to use lsp snippets. i use snippets plugin called coc-snippet  now. To avoid the suggest window auto show the lsp provided  snippets one the top of list，I changed the priority of snippet suggest to 100(Max), so that would be default select. Because I do not want to use <c-n>😂 to select my snippets. I add this to my config file 
 "snippets.priority": 100.

**Comment by codebysandwich** [comment]
> 

this a trick! 👍

**Comment by codebysandwich** [comment]
> 

this's a trick! 👍

**Comment by codebysandwich** [comment]
> @codebysandwich basically, I try not to use lsp snippets. i use snippets plugin called coc-snippet now. To avoid the suggest window auto show the lsp provided snippets one the top of list，I changed the priority of snippet suggest to 100(Max), so that would be default select. Because I do not want to use c-n 😂 to select my snippets. I add this to my config file "snippets.priority": 100.

this a trick! 👍

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
