### ISSUE TITLE
Extract to variable and function

### ISSUE THREAD

**Issue by Phenomendx** [neoclide/coc-java#58]
I've tried to extract to a variable or method and it seem this capabilities are not yet supported, would be great to have these

**Comment by dansomething** [comment]
relates to https://github.com/eclipse/eclipse.jdt.ls/pull/381

**Comment by sven1** [comment]
> relates to [eclipse/eclipse.jdt.ls#381](https://github.com/eclipse/eclipse.jdt.ls/pull/381)

Seems that the Language Server supports variable and method extraction. I don't know the internals of coc-java or any other Language Client, but should it actually not work out of the box? Nevertheless I do not get the option to extract the selected code.

**Comment by dansomething** [comment]
Do you have `coc-codeaction-selected` mapped in your config?

From the [coc.nvim README example config](https://github.com/neoclide/coc.nvim#example-vim-configuration) or `
:help coc-codeaction-selected`:
```
" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)
```

If I select a region of code that can be extracted to a method I get the option. Sometimes the region can't be extracted due to how variables are scoped and I don't get the extract option. Usually I can simply increase the size of region selected to fix the problem or refactor the code to fix scoping issues.

In the screenshot below, I've type the keys `,a$` on line 5 and received `Extract to method` as an option.
<img width="399" alt="Screen Shot 2020-11-13 at 4 39 48 PM" src="https://user-images.githubusercontent.com/92310/99128054-6b161780-25cf-11eb-818a-4d76be28c29a.png">
The result is:
<img width="346" alt="Screen Shot 2020-11-13 at 4 44 42 PM" src="https://user-images.githubusercontent.com/92310/99128113-9a2c8900-25cf-11eb-9700-3e27ab0869d4.png">

**Comment by sven1** [comment]
> Do you have `coc-codeaction-selected` mapped in your config?
> 
> From the [coc.nvim README example config](https://github.com/neoclide/coc.nvim#example-vim-configuration) or ` :help coc-codeaction-selected`:
> 
> ```
> " Applying codeAction to the selected region.
> " Example: `<leader>aap` for current paragraph
> xmap <leader>a  <Plug>(coc-codeaction-selected)
> nmap <leader>a  <Plug>(coc-codeaction-selected)
> ```
> 
> If I select a region of code that can be extracted to a method I get the option. Sometimes the region can't be extracted due to how variables are scoped and I don't get the extract option. Usually I can simply increase the size of region selected to fix the problem or refactor the code to fix scoping issues.
> 
> In the screenshot below, I've type the keys `,a$` on line 5 and received `Extract to method` as an option.
> <img alt="Screen Shot 2020-11-13 at 4 39 48 PM" width="399" src="https://user-images.githubusercontent.com/92310/99128054-6b161780-25cf-11eb-818a-4d76be28c29a.png">
> The result is:
> <img alt="Screen Shot 2020-11-13 at 4 44 42 PM" width="346" src="https://user-images.githubusercontent.com/92310/99128113-9a2c8900-25cf-11eb-9700-3e27ab0869d4.png">

I am sorry, works exactly as you have described. My selected region could somehow not be extracted. Do you use a keybinding to extend or reduce the region?

I'm assuming `coc-range-select` and `coc-range-select-backward` is the equivalent to the eclipse shortcut Alt+Shit+Up/Down.
It works quite reasonably but is far away from the Eclipse quality.

**Comment by dansomething** [comment]
For visual selection expansion then `o` and `O` are your friend. See `:help v_o`. I often use a motion key for the selection such as `<leader>aap`.

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

Request refactor code actions is recommanded like:

```
" Remap keys for applying refactor code actions
nmap <silent> <leader>re <Plug>(coc-codeaction-refactor)
xmap <silent> <leader>r  <Plug>(coc-codeaction-refactor-selected)
nmap <silent> <leader>r  <Plug>(coc-codeaction-refactor-selected)
```
